
#' Parallel Tempering Monte Carlo Function
#'
#' This function performs the Parallel Tempering Monte Carlo (PTMC) simulation. It first validates the provided settings 
#' using the `check_settings` function, then either uses default or provided parameters to run the simulation via the 
#' `get_output` function. The function returns the output of the simulation, which includes various results depending 
#' on the model, data, and settings.
#'
#' @param model A list representing the model to be used in the PTMC simulation. This typically includes information 
#'              such as model parameters, parameter names, and other model-specific settings required for the simulation.
#'
#' @param data A list containing the data used by the model. This could include observed data, prior distributions, 
#'             or other inputs necessary for the PTMC simulation.
#'
#' @param settings A list of settings for the PTMC simulation. The settings must include:
#'   - `numberChainRuns`: The number of parallel chains to run.
#'   - Other relevant settings required by the PTMC process, which will be validated using the `check_settings` function.
#'
#' @param par (Optional) A list of parameters for each chain. If provided, each element of the list corresponds to 
#'            the parameter values for one chain. If not provided (or empty), default parameters are used for the chains.
#'
#' @return A list containing the output of the PTMC simulation. The output is generated by calling the `get_output` function, 
#'         and may include components such as:
#'   - Posterior samples of model parameters
#'   - Discrete model states
#'   - Log-posterior values
#'   - Temperatures for each chain
#'   - Acceptance rates for each chain
#'   - Parameter values for each chain
#'
#' @importFrom coda mcmc
#' @importFrom parallel mclapply
#' @importFrom dplyr gather
#'
#' @export
ptmc_func <- function(model, data, settings, par = NULL) {
  settings <- check_settings(settings, model)

  if (length(par) == 0) {
    par <- rep(list(list(type = "None")), settings[["numberChainRuns"]])
    output <- get_output(model, data, settings, FALSE, par)
  } else {
    output <- get_output(model, data, settings, TRUE, par)
  }
  output
}

#' Get Output from Parallel Tempering Monte Carlo (PTMC) Simulation
#'
#' This function performs the core steps of running multiple chains of the Parallel Tempering Monte Carlo (PTMC) 
#' simulation and processes the results. It either runs the chains in parallel or sequentially, collects the output 
#' from each chain, and organizes it into a list format. The output includes posterior samples, log-posterior values, 
#' temperatures, acceptance rates, and other diagnostic information for each chain.
#'
#' @param model A list representing the model to be used in the PTMC simulation. This typically includes information 
#'              such as model parameters, parameter names, and other model-specific settings required for the simulation.
#'
#' @param data_list A list containing the data used by the model. This could include observed data, prior distributions, 
#'                  or other inputs necessary for the PTMC simulation.
#'
#' @param settings A list of settings for the PTMC simulation. The settings must include:
#'   - `numberChainRuns`: The number of parallel chains to run.
#'   - `runParallel`: Logical, whether to run the chains in parallel.
#'   - `numberFittedPar`: The number of parameters to fit in the model.
#'   - `numberCores`: The number of CPU cores to use for parallel execution (if `runParallel = TRUE`).
#'   - Other relevant settings that influence the PTMC process, such as iteration count, burn-in period, etc.
#'
#' @param update_ind Logical flag indicating whether to update the model parameters. Typically, this is used to specify 
#'                   whether parameters should be updated during the simulation.
#'
#' @param par A list of parameters for each chain. Each element of the list corresponds to the parameter values for one 
#'            chain. If provided, these values are used for the chains; otherwise, the simulation will use default 
#'            parameter values.
#'
#' @return A list containing the processed output of the PTMC simulation, which includes:
#'   - `mcmc`: An `mcmc.list` object containing the posterior samples from each chain.
#'   - `lpost`: A data frame of log-posterior values for each sample and chain.
#'   - `temp`: A data frame of temperatures for each chain.
#'   - `acc`: A data frame of acceptance rates for each chain.
#'   - `outPTpar`: A list of parameter values for each chain during the simulation.
#'
#' @details
#' This function is designed to handle both parallel and sequential execution of PTMC chains. If `runParallel` is `TRUE`,
#' the chains are executed in parallel using the `mclapply` function. Otherwise, the chains are executed sequentially 
#' in a loop. The output is processed and reshaped into appropriate data frames for easy analysis.
#'
#' @importFrom coda mcmc
#' @importFrom parallel mclapply
#' @importFrom dplyr gather
#'
#' @export
get_output <- function(model, data_list, settings, update_ind, par) {
  outPTpost <- vector(mode = "list", length = settings[["numberChainRuns"]])
  outPTlp <- vector(mode = "list", length = settings[["numberChainRuns"]])
  outPTtemp <- vector(mode = "list", length = settings[["numberChainRuns"]])
  outPTacc <- vector(mode = "list", length = settings[["numberChainRuns"]])
  outPTpar <- vector(mode = "list", length = settings[["numberChainRuns"]])

  # Run the chains in parallel
  # Run the chains in parallel
  if (settings[["runParallel"]]) {
    out_raw <- mclapply(1:settings[["numberChainRuns"]], 
      function(i) {
        run_ptmc(model, data_list, settings, update_ind, par[[i]], i)
      },
      mc.cores = settings[["numberCores"]]
    )
  } else {
    for (i in 1:settings[["numberChainRuns"]]) {
      out_raw[[i]] <- run_ptmc(model, data_list, settings, update_ind, par[[i]], i)
    }
  }

  for(i in 1:settings[["numberChainRuns"]]) {
    out_post <- out_raw[[i]][["output"]][, 1:settings$numberFittedPar]
    outPTpar[[i]] <- out_raw[[i]][["PTMCpar"]]
    if (settings$numberFittedPar > 1){
        colnames(out_post) <- model[["namesOfParameters"]]
    }
    outPTpost[[i]] <- mcmc(out_post)
    
    outPTlp[[i]] <- out_raw[[i]][["output"]][, settings$numberFittedPar + 1]
    outPTtemp[[i]] <- out_raw[[i]][["output"]][, settings$numberFittedPar + 2]
    outPTacc[[i]] <- out_raw[[i]][["output"]][, settings$numberFittedPar + 3]
  }

  outlpv <- data.frame(matrix(unlist(outPTlp), nrow = length(outPTlp[[1]])))
  colnames(outlpv) <- c(1:settings[["numberChainRuns"]])
  outlpv <- outlpv %>% gather(colnames(outlpv), key="chain_no",value="lpost")
  outlpv$sample_no <- rep(1:length(outPTlp[[1]]), settings[["numberChainRuns"]])

  outltempv <- data.frame(matrix(unlist(outPTtemp), nrow=length(outPTtemp[[1]])))
  colnames(outltempv) <- c(1:settings[["numberChainRuns"]])
  outltempv <- outltempv %>% gather(colnames(outltempv), key="chain_no", value="temperature")
  outltempv$sample_no <- rep(1:length(outPTtemp[[1]]), settings[["numberChainRuns"]])
  
  outlaccv <- data.frame(matrix(unlist(outPTacc), nrow=length(outPTacc[[1]])))
  colnames(outlaccv) <- c(1:settings[["numberChainRuns"]])
  outlaccv <- outlaccv %>% gather(colnames(outlaccv), key="chain_no", value="acceptance rate")
  outlaccv$sample_no <- rep(1:length(outPTacc[[1]]), settings[["numberChainRuns"]])

  output <- list(
    mcmc = as.mcmc.list(outPTpost),
    lpost = outlpv,
    temp = outltempv,
    acc = outlaccv,
    outPTpar = outPTpar
  )
  output
}

#' Check and Set Default Values for PTMC Simulation Settings
#'
#' This function checks whether all required settings for the Parallel Tempering Monte Carlo (PTMC) simulation are 
#' specified in the `settings` list. If any required settings are missing, it assigns default values and prints 
#' messages to notify the user. If critical settings are missing, it raises an error. This ensures that all settings 
#' are correctly specified before running the simulation.
#'
#' @param settings A list of settings for the PTMC simulation. This list can contain various parameters, including:
#'   - `numberChainRuns`: The number of chains to run (default: 4).
#'   - `numberCores`: The number of CPU cores to use for parallel execution (default: equal to `numberChainRuns`).
#'   - `numberTempChains`: The number of temperature chains to use (default: 10).
#'   - `iterations`: The number of iterations to run (default: 20000).
#'   - `burninPosterior`: The burn-in period for the posterior (default: 10000).
#'   - `thin`: The thinning interval for the MCMC chains (default: 100).
#'   - `consoleUpdates`: The frequency of console updates (default: 100).
#'   - `numberFittedPar`: The number of parameters to fit (MUST be specified by the user).
#'   - `onAdaptiveCov`: A logical flag indicating whether to use adaptive covariance (default: TRUE).
#'   - `updatesAdaptiveCov`: The frequency of adaptive covariance updates (default: 100).
#'   - `burninAdaptiveCov`: The burn-in period for adaptive covariance (default: 2000).
#'   - `onAdaptiveTemp`: A logical flag indicating whether to use adaptive temperatures (default: TRUE).
#'   - `updatesAdaptiveTemp`: The frequency of adaptive temperature updates (default: 10).
#'   - `onDebug`: A logical flag indicating whether to enable debug mode (default: FALSE).
#'   - `lowerParBounds`: The lower bounds for the parameters (MUST be specified by the user).
#'   - `upperParBounds`: The upper bounds for the parameters (MUST be specified by the user).
#'   - `covarInitVal`: The initial covariance value (default: 1e-10).
#'   - `covarInitValAdapt`: The initial covariance value for adaptive updates (default: 1e-10).
#'   - `covarMaxVal`: The maximum covariance value (default: 1).
#'   - `runParallel`: A logical flag indicating whether to run the simulation in parallel (default: TRUE).
#' @param model A list representing the model used in the PTMC simulation. The function checks if specific model-related
#'              attributes are available to fill in missing settings (e.g., `lowerParSupport_fitted`, `upperParSupport_fitted`, 
#'              and `discrete_length`).
#'
#' @return The updated `settings` list, with all required settings specified and missing settings filled with default values.
#'
#' @details
#' This function ensures that the `settings` list contains all necessary values for a successful PTMC simulation. If any 
#' settings are missing, it assigns reasonable default values and notifies the user. Critical settings, such as 
#' `numberFittedPar`, `lowerParBounds`, and `upperParBounds`, must be specified by the user, and an error is raised 
#' if they are missing.
#'
#' @examples
#' # Example usage of check_settings function
#' settings <- list(
#'   numberChainRuns = 5,
#'   numberCores = 5,
#'   numberFittedPar = 3,
#'   lowerParBounds = c(0, 0, 0),
#'   upperParBounds = c(10, 10, 10)
#' )
#' settings <- check_settings(settings, model = NULL)
#' print(settings)
#'
#' @export
check_settings <- function(settings, model) {

  if (is.null(settings[["numberChainRuns"]])) {
    settings[["numberChainRuns"]] <- 4
    cat("`numberChainRuns` not specified in settings. Default value 4. \n")
  }

  if (is.null(settings[["numberCores"]])) {
    settings[["numberCores"]] <- settings[["numberChainRuns"]]
    cat("`numberCores` not specified in settings. Default value equal to `numberChainRuns`. \n")
  }

  if (is.null(settings[["numberTempChains"]])) {
    settings[["numberTempChains"]] <- 10
    cat("`numberTempChains` not specified in settings. Default value 10. \n")
  }  
  if (is.null(settings[["iterations"]])) {
    settings[["iterations"]] <- 20000
    cat("`iterations` not specified in settings. Default value 20,000. \n")
  }  
  if (is.null(settings[["burninPosterior"]])) {
    settings[["burninPosterior"]] <- 10000
    cat("`numberChainRuns` not specified in settings. Default value 10,000. \n")
  }  
  if (is.null(settings[["thin"]])) {
    settings[["thin"]] <- 100
    cat("`thin` not specified in settings. Default value 100. \n")
  }
  if (is.null(settings[["consoleUpdates"]])) {
    settings[["consoleUpdates"]] <- 100
    cat("`consoleUpdates` not specified in settings. Default value 100. \n")
  }
  if (is.null(settings[["numberFittedPar"]])) {
    stop("`numberFittedPar` not specified in settings. MUST be specified. \n")
  }
  if (is.null(settings[["onAdaptiveCov"]])) {
        settings[["onAdaptiveCov"]] <- TRUE
    cat("`onAdaptiveCov` not specified in settings. Default value TRUE. \n")
  }
  if (is.null(settings[["updatesAdaptiveCov"]])) {
        settings[["updatesAdaptiveCov"]] <- 100
    cat("`updatesAdaptiveCov` not specified in settings. Default value 100. \n")
  }
  if (is.null(settings[["burninAdaptiveCov"]])) {
        settings[["burninAdaptiveCov"]] <- 2000
    cat("`burninAdaptiveCov` not specified in settings. Default value 2000. \n")
  }
  if (is.null(settings[["onAdaptiveTemp"]])) {
        settings[["onAdaptiveTemp"]] <- TRUE
    cat("`onAdaptiveTemp` not specified in settings.  Default value TRUE. \n")
  }
  if (is.null(settings[["updatesAdaptiveTemp"]])) {
        settings[["updatesAdaptiveTemp"]] <- 10
    cat("`updatesAdaptiveTemp` not specified in settings.  Default value 10. \n")
  }
  if (is.null(settings[["onDebug"]])) {
        settings[["onDebug"]] <- FALSE
  }
  if (is.null(settings[["lowerParBounds"]])) {
    if (is.null(model$lowerParSupport_fitted)) {
      stop("`lowerParBounds` not specified in settings. MUST be specified. \n")
    } 
    settings[["lowerParBounds"]] <- model$lowerParSupport_fitted
    cat("`lowerParBounds` not specified in settings. Defaults to lowerParSupport_fitted. \n")
  }
  if (is.null(settings[["upperParBounds"]])) {
    if (is.null(model$lowerParSupport_fitted)) {
      stop("`upperParBounds` not specified in settings. MUST be specified. \n")
    } 
    settings[["upperParBounds"]] <- model$upperParSupport_fitted
    cat("`upperParBounds` not specified in settings. Defaults to upperParSupport_fitted \n")
  }
  if (is.null(settings[["covarInitVal"]])) {
        settings[["covarInitVal"]] <- 1e-10
    cat("`covarInitVal` not specified in settings.  Default value 1e-10. \n")
  }
  if (is.null(settings[["covarInitValAdapt"]])) {
        settings[["covarInitValAdapt"]] <- 1e-10
    cat("`covarInitValAdapt` not specified in settings.  Default value 1e-10. \n")
  }
  if (is.null(settings[["covarMaxVal"]])) {
        settings[["covarMaxVal"]] <- 1
    cat("`covarMaxVal` not specified in settings. Default value 1. \n")
  }
  if (is.null(settings[["runParallel"]])) {
        settings[["runParallel"]] <- TRUE
    cat("`runParallel` not specified in settings. Default value TRUE. \n")
  }

  settings
}